**PROJECT**:
Prediction of species of flower given the properties of flower (i.e sepal_length,sepal_width,petal_length and petal_width), using Linear Regression in three different methods:-
1. using inbuilt LinearRegression function from sklearn Library
2. Analytical method using numpy
3. Gradient Descent method using numpy


**Dataset**:
Iris Dataset

In [1]:
#importing all the necessary libraries and functions
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [2]:
#loading the data and converting it into a pandas dataframe. This dataset is available in the sklearn library
data=load_iris()
df=pd.DataFrame(data['data'],columns=data['feature_names'])
df['species']=data['target']

In [3]:
df.head()#checking the top 5 rows of data.

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [4]:
#Splitting the data into two parts, i.e Training data and testing data (test_size indicates the ratio of testing to total data)
#x should be the properties of flowers which would be used to predict the species (called properites or attributes) and y should
#be the column which we are going to predict.
xt,xte,yt,yte=train_test_split(df.drop("species",axis=1),df["species"],test_size=0.2)

**Method - I using sklearn**

In [5]:
#creating a linear regression model using the training dataset
model=LinearRegression()
model.fit(xt,yt)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [6]:
#Now that we have created the model, we have to test it on the testing dataset to know how it works on data which is not in the 
#training dataset
pred=model.predict(xte)

In [7]:
#calculating MSE of the predicted and actual values
print(np.sqrt(metrics.mean_squared_error(pred,yte)))

0.23981324037015028


In [8]:
#rounding all the predicted values to their nearest integers
pred=[int(round(i)) for i in pred]

In [9]:
pred

[2,
 1,
 2,
 2,
 1,
 0,
 0,
 0,
 2,
 2,
 1,
 0,
 2,
 1,
 1,
 1,
 2,
 2,
 0,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 0,
 0,
 2]

In [10]:
#Complete report of the model to know how good the model is , in this case its 93% accurate.
print(metrics.classification_report(yte,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.82      1.00      0.90         9
           2       1.00      0.86      0.92        14

    accuracy                           0.93        30
   macro avg       0.94      0.95      0.94        30
weighted avg       0.95      0.93      0.93        30



In [11]:
print(metrics.confusion_matrix(yte,pred))

[[ 7  0  0]
 [ 0  9  0]
 [ 0  2 12]]


**Method - II, Analytical method**

In [12]:
from numpy.linalg import inv

In [13]:
#the matrix equation for linear regression is Y=W.X where Y is the target column, W is the coefficients and X are the 
# variables.
#after multiplying the regression equation with (X_transpose/(X_transpose.X)) we get W=inverse(X_transpose*X).X_transpose.Y
#By using training dataset on the above equation we can find W which can be used afterwards to predict on the test dataset.

In [14]:
xt.shape

(120, 4)

In [15]:
w=inv(xt.T.dot(xt)).dot(xt.T).dot(yt)

In [16]:
w

array([-0.09332335, -0.0065998 ,  0.21543878,  0.61947813])

In [17]:
preds=xte.dot(w)

In [18]:
preds.shape


(30,)

In [19]:
print(np.sqrt(metrics.mean_squared_error(preds,yte)))

0.23769355638930717


In [20]:
print(preds)

110    1.709973
95     1.096474
112    1.831419
139    1.799883
51     1.280303
39    -0.051335
19     0.007973
48    -0.071979
125    1.714646
128    1.891612
119    1.431951
26     0.103437
114    2.025730
69     0.982527
71     1.079325
94     1.169734
123    1.564954
104    1.985996
20    -0.036244
133    1.421538
100    2.231612
78     1.319612
82     1.024490
122    1.945327
103    1.714441
64     1.039151
72     1.380431
18    -0.004933
16    -0.001824
147    1.732837
dtype: float64


In [21]:
ls=np.array([round(i) for i in preds])

In [22]:
ls

array([2, 1, 2, 2, 1, 0, 0, 0, 2, 2, 1, 0, 2, 1, 1, 1, 2, 2, 0, 1, 2, 1,
       1, 2, 2, 1, 1, 0, 0, 2])

In [23]:
metrics.accuracy_score(ls,yte)

0.9333333333333333

In [24]:
print(metrics.classification_report(ls,yte))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      0.82      0.90        11
           2       0.86      1.00      0.92        12

    accuracy                           0.93        30
   macro avg       0.95      0.94      0.94        30
weighted avg       0.94      0.93      0.93        30



**Method - III, Gradient Descent**

In [25]:
#Procedure for gradient descent method
#1. randomly initialize a coefficient matrix
#2. Define the loss function 
#3. Find the gradient of the loss function and take a small step in the opposite direction of the gradient in order to minimise
# the gradient untill we reach the minimum value
#4. When we reach the minimum point at that point the we will get the coefficient matrix which can be used to predict target values
#of unseen data 

In [26]:
A=np.random.normal(size=[4,1])
A

array([[ 0.12255832],
       [ 1.50303287],
       [-0.23293811],
       [-0.55597148]])

In [27]:
x=np.array(data['data'])

In [28]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [29]:
y=np.array(data['target'])

In [30]:
y=y.reshape(150,1)
y.shape

(150, 1)

In [31]:

l=x.dot(A)-y
l

array([[ 5.44835485],
       [ 4.67232675],
       [ 4.97171547],
       [ 4.76256873],
       [ 5.58640231],
       [ 5.90525977],
       [ 5.18117526],
       [ 5.26250192],
       [ 4.4607443 ],
       [ 4.85493338],
       [ 5.76243511],
       [ 5.21469645],
       [ 4.71566807],
       [ 4.72427034],
       [ 6.33224974],
       [ 6.74013133],
       [ 5.99843501],
       [ 5.3927577 ],
       [ 5.84732113],
       [ 5.82037376],
       [ 5.26493763],
       [ 5.61447332],
       [ 5.63055422],
       [ 4.9110754 ],
       [ 5.14481502],
       [ 4.63799496],
       [ 5.12801382],
       [ 5.43731687],
       [ 5.3103074 ],
       [ 4.90183404],
       [ 4.76378659],
       [ 5.20033096],
       [ 6.39473375],
       [ 6.54950119],
       [ 4.79933623],
       [ 5.03177678],
       [ 5.52067199],
       [ 5.62974362],
       [ 4.6343414 ],
       [ 5.27475775],
       [ 5.40379568],
       [ 3.53887708],
       [ 4.93494798],
       [ 5.16712281],
       [ 5.67160137],
       [ 4

In [32]:
l=(np.linalg.norm(l))**2

In [33]:
l

1701.8609508343

In [34]:
#gradient=2*x.T.dot((x.dot(A)-y))

In [35]:
#gradient.shape

In [36]:
while True:
    gradient=2*x.T.dot((x.dot(A)-y))
    A=A-0.0001*gradient
    loss=np.linalg.norm((x.dot(A)-y))**2
    print(A.shape)
    print(loss)
    if loss>l:
        break
    l=loss

(4, 1)
1348.4702921992393
(4, 1)
1081.0927672943164
(4, 1)
876.7280758749678
(4, 1)
718.828573726383
(4, 1)
595.4487210385173
(4, 1)
497.930365311758
(4, 1)
419.9680700510714
(4, 1)
356.94407282536054
(4, 1)
305.45460464602183
(4, 1)
262.9720823976258
(4, 1)
227.60382843706972
(4, 1)
197.91941132195757
(4, 1)
172.8268096534485
(4, 1)
151.48334830156355
(4, 1)
133.2314307886508
(4, 1)
117.55198074431904
(4, 1)
104.03055443437329
(4, 1)
92.33254007228886
(4, 1)
82.18489130017608
(4, 1)
73.36257471301101
(4, 1)
65.6784316394579
(4, 1)
58.975524271158044
(4, 1)
53.121299369734295
(4, 1)
48.00309016678899
(4, 1)
43.524610676548946
(4, 1)
39.6031920413621
(4, 1)
36.16757877507608
(4, 1)
33.1561516961072
(4, 1)
30.51547951282649
(4, 1)
28.199126387572484
(4, 1)
26.166661167125763
(4, 1)
24.382827320563084
(4, 1)
22.816842388278875
(4, 1)
21.44180292844272
(4, 1)
20.23417626914255
(4, 1)
19.173364349888107
(4, 1)
18.241327932586902
(4, 1)
17.422261743004647
(4, 1)
16.702312858401953
(4, 1)
16.

8.386809959039914
(4, 1)
8.384760493759789
(4, 1)
8.382714322800796
(4, 1)
8.380671439650397
(4, 1)
8.37863183781408
(4, 1)
8.37659551081529
(4, 1)
8.374562452195338
(4, 1)
8.372532655513393
(4, 1)
8.370506114346346
(4, 1)
8.36848282228879
(4, 1)
8.366462772952941
(4, 1)
8.364445959968565
(4, 1)
8.362432376982913
(4, 1)
8.360422017660674
(4, 1)
8.358414875683886
(4, 1)
8.35641094475188
(4, 1)
8.35441021858124
(4, 1)
8.352412690905687
(4, 1)
8.35041835547606
(4, 1)
8.348427206060247
(4, 1)
8.346439236443082
(4, 1)
8.344454440426343
(4, 1)
8.342472811828644
(4, 1)
8.340494344485387
(4, 1)
8.338519032248708
(4, 1)
8.336546868987396
(4, 1)
8.334577848586843
(4, 1)
8.332611964948992
(4, 1)
8.33064921199226
(4, 1)
8.328689583651478
(4, 1)
8.326733073877838
(4, 1)
8.32477967663884
(4, 1)
8.322829385918205
(4, 1)
8.320882195715853
(4, 1)
8.3189381000478
(4, 1)
8.316997092946137
(4, 1)
8.315059168458953
(4, 1)
8.313124320650282
(4, 1)
8.311192543600022
(4, 1)
8.309263831403928
(4, 1)
8.30733817

(4, 1)
7.59932642938249
(4, 1)
7.598470684073949
(4, 1)
7.597616178079609
(4, 1)
7.59676290952553
(4, 1)
7.595910876540989
(4, 1)
7.595060077258459
(4, 1)
7.594210509813612
(4, 1)
7.593362172345284
(4, 1)
7.592515062995509
(4, 1)
7.591669179909475
(4, 1)
7.59082452123554
(4, 1)
7.589981085125212
(4, 1)
7.589138869733153
(4, 1)
7.588297873217165
(4, 1)
7.587458093738179
(4, 1)
7.58661952946026
(4, 1)
7.58578217855059
(4, 1)
7.584946039179469
(4, 1)
7.584111109520301
(4, 1)
7.583277387749584
(4, 1)
7.582444872046913
(4, 1)
7.5816135605949775
(4, 1)
7.580783451579541
(4, 1)
7.579954543189435
(4, 1)
7.579126833616561
(4, 1)
7.578300321055879
(4, 1)
7.577475003705407
(4, 1)
7.576650879766199
(4, 1)
7.575827947442361
(4, 1)
7.575006204941016
(4, 1)
7.5741856504723275
(4, 1)
7.573366282249468
(4, 1)
7.572548098488629
(4, 1)
7.571731097409014
(4, 1)
7.570915277232808
(4, 1)
7.570100636185204
(4, 1)
7.569287172494382
(4, 1)
7.568474884391501
(4, 1)
7.567663770110679
(4, 1)
7.566853827889025
(4,

(4, 1)
7.258013523495167
(4, 1)
7.25764728577027
(4, 1)
7.25728156968001
(4, 1)
7.256916374476758
(4, 1)
7.256551699413993
(4, 1)
7.256187543746269
(4, 1)
7.255823906729241
(4, 1)
7.255460787619652
(4, 1)
7.255098185675325
(4, 1)
7.254736100155177
(4, 1)
7.254374530319199
(4, 1)
7.254013475428473
(4, 1)
7.253652934745158
(4, 1)
7.253292907532493
(4, 1)
7.252933393054789
(4, 1)
7.252574390577432
(4, 1)
7.252215899366891
(4, 1)
7.251857918690695
(4, 1)
7.251500447817449
(4, 1)
7.251143486016829
(4, 1)
7.250787032559569
(4, 1)
7.250431086717484
(4, 1)
7.25007564776343
(4, 1)
7.249720714971348
(4, 1)
7.2493662876162235
(4, 1)
7.249012364974106
(4, 1)
7.248658946322098
(4, 1)
7.24830603093837
(4, 1)
7.2479536181021285
(4, 1)
7.247601707093646
(4, 1)
7.247250297194236
(4, 1)
7.246899387686266
(4, 1)
7.246548977853151
(4, 1)
7.246199066979344
(4, 1)
7.245849654350357
(4, 1)
7.245500739252733
(4, 1)
7.245152320974052
(4, 1)
7.24480439880294
(4, 1)
7.244456972029064
(4, 1)
7.244110039943123
(4,

7.11188401841376
(4, 1)
7.111725633393017
(4, 1)
7.111567473444009
(4, 1)
7.1114095382466305
(4, 1)
7.111251827481219
(4, 1)
7.111094340828579
(4, 1)
7.1109370779699645
(4, 1)
7.110780038587084
(4, 1)
7.110623222362099
(4, 1)
7.11046662897764
(4, 1)
7.110310258116759
(4, 1)
7.110154109462983
(4, 1)
7.109998182700293
(4, 1)
7.109842477513107
(4, 1)
7.109686993586297
(4, 1)
7.109531730605188
(4, 1)
7.109376688255558
(4, 1)
7.109221866223618
(4, 1)
7.109067264196045
(4, 1)
7.108912881859947
(4, 1)
7.108758718902885
(4, 1)
7.1086047750128705
(4, 1)
7.10845104987835
(4, 1)
7.10829754318822
(4, 1)
7.108144254631821
(4, 1)
7.107991183898936
(4, 1)
7.107838330679788
(4, 1)
7.107685694665044
(4, 1)
7.107533275545811
(4, 1)
7.107381073013637
(4, 1)
7.10722908676051
(4, 1)
7.107077316478858
(4, 1)
7.106925761861547
(4, 1)
7.106774422601875
(4, 1)
7.106623298393591
(4, 1)
7.106472388930863
(4, 1)
7.1063216939083125
(4, 1)
7.106171213020987
(4, 1)
7.106020945964362
(4, 1)
7.105870892434367
(4, 1)
7

7.0486569757550726
(4, 1)
7.048588422364251
(4, 1)
7.0485199663599865
(4, 1)
7.048451607603912
(4, 1)
7.04838334595786
(4, 1)
7.048315181283869
(4, 1)
7.048247113444158
(4, 1)
7.048179142301147
(4, 1)
7.0481112677174576
(4, 1)
7.0480434895559
(4, 1)
7.047975807679484
(4, 1)
7.047908221951409
(4, 1)
7.047840732235074
(4, 1)
7.04777333839407
(4, 1)
7.047706040292184
(4, 1)
7.047638837793384
(4, 1)
7.047571730761854
(4, 1)
7.047504719061956
(4, 1)
7.047437802558242
(4, 1)
7.047370981115465
(4, 1)
7.047304254598568
(4, 1)
7.047237622872684
(4, 1)
7.047171085803144
(4, 1)
7.047104643255458
(4, 1)
7.047038295095337
(4, 1)
7.046972041188679
(4, 1)
7.046905881401579
(4, 1)
7.046839815600313
(4, 1)
7.046773843651353
(4, 1)
7.046707965421356
(4, 1)
7.046642180777176
(4, 1)
7.046576489585847
(4, 1)
7.0465108917146
(4, 1)
7.04644538703085
(4, 1)
7.046379975402205
(4, 1)
7.046314656696454
(4, 1)
7.04624943078158
(4, 1)
7.046184297525751
(4, 1)
7.046119256797325
(4, 1)
7.0460543084648455
(4, 1)
7.04

(4, 1)
7.020190204108221
(4, 1)
7.020162089395649
(4, 1)
7.02013401462092
(4, 1)
7.020105979727301
(4, 1)
7.020077984658137
(4, 1)
7.020050029356862
(4, 1)
7.020022113766974
(4, 1)
7.019994237832066
(4, 1)
7.019966401495807
(4, 1)
7.019938604701942
(4, 1)
7.0199108473943
(4, 1)
7.019883129516792
(4, 1)
7.019855451013399
(4, 1)
7.019827811828194
(4, 1)
7.019800211905323
(4, 1)
7.019772651189008
(4, 1)
7.019745129623558
(4, 1)
7.019717647153353
(4, 1)
7.019690203722859
(4, 1)
7.01966279927662
(4, 1)
7.0196354337592535
(4, 1)
7.0196081071154595
(4, 1)
7.0195808192900175
(4, 1)
7.019553570227785
(4, 1)
7.019526359873695
(4, 1)
7.019499188172763
(4, 1)
7.019472055070073
(4, 1)
7.019444960510802
(4, 1)
7.019417904440195
(4, 1)
7.019390886803576
(4, 1)
7.01936390754635
(4, 1)
7.019336966613993
(4, 1)
7.019310063952067
(4, 1)
7.019283199506209
(4, 1)
7.019256373222122
(4, 1)
7.0192295850456015
(4, 1)
7.019202834922511
(4, 1)
7.019176122798799
(4, 1)
7.019149448620481
(4, 1)
7.019122812333653
(

(4, 1)
7.009263333902397
(4, 1)
7.009250741109943
(4, 1)
7.009238166205858
(4, 1)
7.009225609164734
(4, 1)
7.009213069961193
(4, 1)
7.0092005485699
(4, 1)
7.009188044965548
(4, 1)
7.0091755591228715
(4, 1)
7.0091630910166405
(4, 1)
7.009150640621665
(4, 1)
7.009138207912775
(4, 1)
7.009125792864854
(4, 1)
7.009113395452813
(4, 1)
7.009101015651598
(4, 1)
7.009088653436196
(4, 1)
7.009076308781624
(4, 1)
7.009063981662931
(4, 1)
7.009051672055215
(4, 1)
7.0090393799335935
(4, 1)
7.009027105273237
(4, 1)
7.0090148480493335
(4, 1)
7.0090026082371155
(4, 1)
7.008990385811852
(4, 1)
7.008978180748841
(4, 1)
7.008965993023419
(4, 1)
7.008953822610959
(4, 1)
7.0089416694868705
(4, 1)
7.008929533626584
(4, 1)
7.008917415005588
(4, 1)
7.008905313599392
(4, 1)
7.008893229383537
(4, 1)
7.008881162333601
(4, 1)
7.008869112425209
(4, 1)
7.008857079634004
(4, 1)
7.008845063935671
(4, 1)
7.008833065305932
(4, 1)
7.008821083720541
(4, 1)
7.008809119155283
(4, 1)
7.0087971715859805
(4, 1)
7.00878524098

(4, 1)
7.004374749235633
(4, 1)
7.00436910079448
(4, 1)
7.004363460377076
(4, 1)
7.0043578279720125
(4, 1)
7.004352203567913
(4, 1)
7.004346587153411
(4, 1)
7.004340978717161
(4, 1)
7.004335378247824
(4, 1)
7.004329785734084
(4, 1)
7.004324201164639
(4, 1)
7.00431862452821
(4, 1)
7.004313055813523
(4, 1)
7.004307495009325
(4, 1)
7.00430194210438
(4, 1)
7.004296397087464
(4, 1)
7.0042908599473765
(4, 1)
7.004285330672929
(4, 1)
7.0042798092529415
(4, 1)
7.004274295676263
(4, 1)
7.0042687899317455
(4, 1)
7.0042632920082735
(4, 1)
7.004257801894722
(4, 1)
7.004252319580014
(4, 1)
7.004246845053057
(4, 1)
7.004241378302796
(4, 1)
7.004235919318183
(4, 1)
7.00423046808818
(4, 1)
7.004225024601781
(4, 1)
7.004219588847981
(4, 1)
7.004214160815798
(4, 1)
7.004208740494261
(4, 1)
7.0042033278724185
(4, 1)
7.00419792293933
(4, 1)
7.004192525684075
(4, 1)
7.004187136095753
(4, 1)
7.004181754163462
(4, 1)
7.004176379876335
(4, 1)
7.004171013223508
(4, 1)
7.004165654194136
(4, 1)
7.004160302777392

7.002176932366677
(4, 1)
7.002174405975698
(4, 1)
7.002171883173519
(4, 1)
7.002169363955037
(4, 1)
7.002166848315162
(4, 1)
7.002164336248817
(4, 1)
7.00216182775092
(4, 1)
7.002159322816402
(4, 1)
7.0021568214402
(4, 1)
7.002154323617257
(4, 1)
7.0021518293425355
(4, 1)
7.002149338610993
(4, 1)
7.002146851417586
(4, 1)
7.002144367757298
(4, 1)
7.002141887625104
(4, 1)
7.002139411015996
(4, 1)
7.002136937924972
(4, 1)
7.002134468347031
(4, 1)
7.002132002277184
(4, 1)
7.002129539710445
(4, 1)
7.002127080641836
(4, 1)
7.002124625066394
(4, 1)
7.002122172979158
(4, 1)
7.002119724375163
(4, 1)
7.002117279249468
(4, 1)
7.002114837597133
(4, 1)
7.00211239941322
(4, 1)
7.002109964692809
(4, 1)
7.002107533430971
(4, 1)
7.002105105622796
(4, 1)
7.0021026812633815
(4, 1)
7.002100260347825
(4, 1)
7.002097842871235
(4, 1)
7.002095428828726
(4, 1)
7.002093018215422
(4, 1)
7.002090611026449
(4, 1)
7.0020882072569455
(4, 1)
7.00208580690205
(4, 1)
7.002083409956917
(4, 1)
7.002081016416701
(4, 1)
7.

(4, 1)
7.001177127589439
(4, 1)
7.001176021444412
(4, 1)
7.001174916870682
(4, 1)
7.001173813866031
(4, 1)
7.001172712428221
(4, 1)
7.001171612555029
(4, 1)
7.001170514244233
(4, 1)
7.001169417493609
(4, 1)
7.001168322300953
(4, 1)
7.0011672286640385
(4, 1)
7.00116613658066
(4, 1)
7.001165046048616
(4, 1)
7.001163957065695
(4, 1)
7.001162869629701
(4, 1)
7.001161783738432
(4, 1)
7.001160699389699
(4, 1)
7.001159616581306
(4, 1)
7.00115853531107
(4, 1)
7.001157455576805
(4, 1)
7.001156377376321
(4, 1)
7.001155300707456
(4, 1)
7.001154225568017
(4, 1)
7.0011531519558385
(4, 1)
7.0011520798687545
(4, 1)
7.001151009304596
(4, 1)
7.001149940261194
(4, 1)
7.001148872736394
(4, 1)
7.00114780672804
(4, 1)
7.001146742233976
(4, 1)
7.001145679252049
(4, 1)
7.001144617780112
(4, 1)
7.001143557816018
(4, 1)
7.001142499357635
(4, 1)
7.001141442402812
(4, 1)
7.0011403869494195
(4, 1)
7.00113933299532
(4, 1)
7.001138280538393
(4, 1)
7.001137229576501
(4, 1)
7.001136180107525
(4, 1)
7.0011351321293445

(4, 1)
7.000748213368579
(4, 1)
7.00074771650617
(4, 1)
7.000747220349569
(4, 1)
7.0007467248977715
(4, 1)
7.000746230149769
(4, 1)
7.000745736104573
(4, 1)
7.000745242761175
(4, 1)
7.000744750118588
(4, 1)
7.000744258175809
(4, 1)
7.000743766931845
(4, 1)
7.000743276385705
(4, 1)
7.0007427865364
(4, 1)
7.0007422973829305
(4, 1)
7.000741808924322
(4, 1)
7.000741321159576
(4, 1)
7.000740834087715
(4, 1)
7.00074034770775
(4, 1)
7.000739862018695
(4, 1)
7.000739377019577
(4, 1)
7.0007388927094105
(4, 1)
7.000738409087216
(4, 1)
7.000737926152018
(4, 1)
7.000737443902842
(4, 1)
7.0007369623387135
(4, 1)
7.000736481458656
(4, 1)
7.000736001261701
(4, 1)
7.000735521746879
(4, 1)
7.000735042913212
(4, 1)
7.000734564759747
(4, 1)
7.000734087285502
(4, 1)
7.000733610489527
(4, 1)
7.000733134370852
(4, 1)
7.000732658928513
(4, 1)
7.000732184161548
(4, 1)
7.000731710069003
(4, 1)
7.000731236649919
(4, 1)
7.000730763903338
(4, 1)
7.000730291828304
(4, 1)
7.000729820423857
(4, 1)
7.00072934968906
(

7.000558482486668
(4, 1)
7.0005582551413905
(4, 1)
7.00055802811906
(4, 1)
7.000557801419222
(4, 1)
7.0005575750414195
(4, 1)
7.000557348985189
(4, 1)
7.0005571232500765
(4, 1)
7.000556897835627
(4, 1)
7.000556672741384
(4, 1)
7.000556447966889
(4, 1)
7.000556223511696
(4, 1)
7.000555999375346
(4, 1)
7.000555775557389
(4, 1)
7.0005555520573655
(4, 1)
7.00055532887483
(4, 1)
7.0005551060093305
(4, 1)
7.000554883460419
(4, 1)
7.0005546612276435
(4, 1)
7.0005544393105525
(4, 1)
7.000554217708703
(4, 1)
7.000553996421643
(4, 1)
7.000553775448924
(4, 1)
7.000553554790106
(4, 1)
7.000553334444736
(4, 1)
7.000553114412369
(4, 1)
7.000552894692567
(4, 1)
7.00055267528488
(4, 1)
7.000552456188871
(4, 1)
7.000552237404089
(4, 1)
7.000552018930095
(4, 1)
7.000551800766453
(4, 1)
7.000551582912715
(4, 1)
7.000551365368439
(4, 1)
7.000551148133195
(4, 1)
7.00055093120654
(4, 1)
7.000550714588032
(4, 1)
7.000550498277236
(4, 1)
7.000550282273713
(4, 1)
7.000550066577028
(4, 1)
7.000549851186745
(4, 

(4, 1)
7.000471773047654
(4, 1)
7.000471668875151
(4, 1)
7.000471564850627
(4, 1)
7.000471460973873
(4, 1)
7.0004713572446775
(4, 1)
7.000471253662831
(4, 1)
7.000471150228127
(4, 1)
7.000471046940354
(4, 1)
7.0004709437993
(4, 1)
7.000470840804768
(4, 1)
7.000470737956537
(4, 1)
7.000470635254405
(4, 1)
7.000470532698165
(4, 1)
7.000470430287607
(4, 1)
7.0004703280225264
(4, 1)
7.000470225902714
(4, 1)
7.000470123927966
(4, 1)
7.000470022098079
(4, 1)
7.000469920412839
(4, 1)
7.0004698188720464
(4, 1)
7.000469717475498
(4, 1)
7.000469616222978
(4, 1)
7.000469515114297
(4, 1)
7.000469414149243
(4, 1)
7.000469313327607
(4, 1)
7.000469212649198
(4, 1)
7.000469112113801
(4, 1)
7.000469011721215
(4, 1)
7.000468911471239
(4, 1)
7.000468811363672
(4, 1)
7.00046871139831
(4, 1)
7.00046861157495
(4, 1)
7.000468511893392
(4, 1)
7.000468412353437
(4, 1)
7.000468312954879
(4, 1)
7.000468213697516
(4, 1)
7.000468114581154
(4, 1)
7.000468015605587
(4, 1)
7.000467916770619
(4, 1)
7.000467818076049
(

(4, 1)
7.000432137347959
(4, 1)
7.000432089478888
(4, 1)
7.000432041677817
(4, 1)
7.000431993944651
(4, 1)
7.000431946279286
(4, 1)
7.000431898681636
(4, 1)
7.000431851151594
(4, 1)
7.0004318036890725
(4, 1)
7.000431756293974
(4, 1)
7.000431708966202
(4, 1)
7.000431661705656
(4, 1)
7.00043161451225
(4, 1)
7.000431567385878
(4, 1)
7.000431520326452
(4, 1)
7.000431473333877
(4, 1)
7.0004314264080545
(4, 1)
7.000431379548892
(4, 1)
7.000431332756292
(4, 1)
7.000431286030164
(4, 1)
7.0004312393704105
(4, 1)
7.000431192776939
(4, 1)
7.000431146249654
(4, 1)
7.00043109978846
(4, 1)
7.000431053393269
(4, 1)
7.000431007063982
(4, 1)
7.000430960800507
(4, 1)
7.000430914602751
(4, 1)
7.00043086847062
(4, 1)
7.000430822404019
(4, 1)
7.000430776402859
(4, 1)
7.000430730467042
(4, 1)
7.00043068459648
(4, 1)
7.000430638791077
(4, 1)
7.000430593050741
(4, 1)
7.000430547375381
(4, 1)
7.000430501764902
(4, 1)
7.0004304562192186
(4, 1)
7.000430410738231
(4, 1)
7.0004303653218525
(4, 1)
7.000430319969984

7.000413640525183
(4, 1)
7.000413618931279
(4, 1)
7.000413597368051
(4, 1)
7.00041357583545
(4, 1)
7.000413554333442
(4, 1)
7.000413532861976
(4, 1)
7.000413511421012
(4, 1)
7.000413490010505
(4, 1)
7.000413468630413
(4, 1)
7.000413447280689
(4, 1)
7.000413425961292
(4, 1)
7.000413404672184
(4, 1)
7.000413383413315
(4, 1)
7.000413362184646
(4, 1)
7.000413340986132
(4, 1)
7.000413319817732
(4, 1)
7.0004132986794
(4, 1)
7.0004132775710985
(4, 1)
7.000413256492781
(4, 1)
7.0004132354444035
(4, 1)
7.000413214425925
(4, 1)
7.000413193437308
(4, 1)
7.000413172478502
(4, 1)
7.00041315154947
(4, 1)
7.000413130650168
(4, 1)
7.000413109780555
(4, 1)
7.000413088940588
(4, 1)
7.000413068130225
(4, 1)
7.00041304734942
(4, 1)
7.000413026598139
(4, 1)
7.000413005876332
(4, 1)
7.000412985183964
(4, 1)
7.0004129645209865
(4, 1)
7.000412943887363
(4, 1)
7.00041292328305
(4, 1)
7.000412902708009
(4, 1)
7.000412882162192
(4, 1)
7.000412861645561
(4, 1)
7.0004128411580755
(4, 1)
7.0004128206996885
(4, 1)
7

7.000405325850904
(4, 1)
7.000405316068187
(4, 1)
7.00040530629937
(4, 1)
7.00040529654443
(4, 1)
7.000405286803343
(4, 1)
7.000405277076098
(4, 1)
7.000405267362668
(4, 1)
7.000405257663035
(4, 1)
7.000405247977184
(4, 1)
7.00040523830509
(4, 1)
7.000405228646737
(4, 1)
7.000405219002102
(4, 1)
7.000405209371168
(4, 1)
7.000405199753915
(4, 1)
7.0004051901503255
(4, 1)
7.000405180560375
(4, 1)
7.000405170984049
(4, 1)
7.000405161421328
(4, 1)
7.000405151872187
(4, 1)
7.000405142336614
(4, 1)
7.000405132814585
(4, 1)
7.000405123306083
(4, 1)
7.000405113811086
(4, 1)
7.000405104329581
(4, 1)
7.000405094861542
(4, 1)
7.000405085406952
(4, 1)
7.000405075965792
(4, 1)
7.000405066538046
(4, 1)
7.000405057123691
(4, 1)
7.000405047722709
(4, 1)
7.000405038335081
(4, 1)
7.000405028960789
(4, 1)
7.000405019599815
(4, 1)
7.0004050102521385
(4, 1)
7.000405000917738
(4, 1)
7.000404991596597
(4, 1)
7.0004049822887
(4, 1)
7.000404972994022
(4, 1)
7.000404963712549
(4, 1)
7.00040495444426
(4, 1)
7.00

7.000401506273874
(4, 1)
7.000401501916956
(4, 1)
7.000401497566227
(4, 1)
7.000401493221682
(4, 1)
7.0004014888833055
(4, 1)
7.000401484551093
(4, 1)
7.000401480225032
(4, 1)
7.000401475905119
(4, 1)
7.000401471591342
(4, 1)
7.000401467283695
(4, 1)
7.000401462982162
(4, 1)
7.000401458686742
(4, 1)
7.000401454397424
(4, 1)
7.0004014501141985
(4, 1)
7.000401445837059
(4, 1)
7.000401441565993
(4, 1)
7.000401437300994
(4, 1)
7.000401433042057
(4, 1)
7.000401428789168
(4, 1)
7.000401424542318
(4, 1)
7.000401420301504
(4, 1)
7.000401416066712
(4, 1)
7.000401411837935
(4, 1)
7.0004014076151675
(4, 1)
7.000401403398397
(4, 1)
7.000401399187618
(4, 1)
7.000401394982816
(4, 1)
7.000401390783995
(4, 1)
7.0004013865911325
(4, 1)
7.0004013824042275
(4, 1)
7.000401378223271
(4, 1)
7.0004013740482565
(4, 1)
7.000401369879164
(4, 1)
7.000401365715999
(4, 1)
7.0004013615587475
(4, 1)
7.000401357407402
(4, 1)
7.000401353261953
(4, 1)
7.000401349122396
(4, 1)
7.000401344988715
(4, 1)
7.000401340860908


7.0003997370063225
(4, 1)
7.000399735162694
(4, 1)
7.000399733321681
(4, 1)
7.0003997314832835
(4, 1)
7.000399729647497
(4, 1)
7.0003997278143215
(4, 1)
7.000399725983747
(4, 1)
7.000399724155772
(4, 1)
7.000399722330395
(4, 1)
7.000399720507609
(4, 1)
7.000399718687416
(4, 1)
7.0003997168698096
(4, 1)
7.000399715054782
(4, 1)
7.000399713242333
(4, 1)
7.000399711432459
(4, 1)
7.000399709625157
(4, 1)
7.0003997078204225
(4, 1)
7.00039970601825
(4, 1)
7.000399704218639
(4, 1)
7.000399702421582
(4, 1)
7.00039970062708
(4, 1)
7.000399698835125
(4, 1)
7.000399697045717
(4, 1)
7.000399695258849
(4, 1)
7.000399693474519
(4, 1)
7.0003996916927305
(4, 1)
7.000399689913466
(4, 1)
7.000399688136731
(4, 1)
7.000399686362523
(4, 1)
7.000399684590829
(4, 1)
7.000399682821658
(4, 1)
7.000399681054997
(4, 1)
7.000399679290845
(4, 1)
7.0003996775292
(4, 1)
7.000399675770057
(4, 1)
7.000399674013413
(4, 1)
7.000399672259266
(4, 1)
7.000399670507611
(4, 1)
7.000399668758441
(4, 1)
7.000399667011756
(4, 1

7.000399015535313
(4, 1)
7.00039901471655
(4, 1)
7.000399013898948
(4, 1)
7.000399013082506
(4, 1)
7.00039901226723
(4, 1)
7.000399011453105
(4, 1)
7.000399010640137
(4, 1)
7.000399009828326
(4, 1)
7.000399009017668
(4, 1)
7.000399008208161
(4, 1)
7.000399007399806
(4, 1)
7.000399006592599
(4, 1)
7.000399005786535
(4, 1)
7.000399004981618
(4, 1)
7.000399004177847
(4, 1)
7.000399003375216
(4, 1)
7.000399002573725
(4, 1)
7.000399001773373
(4, 1)
7.000399000974157
(4, 1)
7.000399000176073
(4, 1)
7.000398999379129
(4, 1)
7.000398998583315
(4, 1)
7.000398997788632
(4, 1)
7.000398996995075
(4, 1)
7.000398996202649
(4, 1)
7.000398995411342
(4, 1)
7.000398994621164
(4, 1)
7.000398993832109
(4, 1)
7.000398993044175
(4, 1)
7.000398992257359
(4, 1)
7.00039899147166
(4, 1)
7.000398990687079
(4, 1)
7.000398989903612
(4, 1)
7.000398989121258
(4, 1)
7.000398988340015
(4, 1)
7.000398987559882
(4, 1)
7.000398986780855
(4, 1)
7.000398986002936
(4, 1)
7.000398985226122
(4, 1)
7.000398984450414
(4, 1)
7.0

(4, 1)
7.0003986933138815
(4, 1)
7.000398692952838
(4, 1)
7.0003986925923085
(4, 1)
7.000398692232289
(4, 1)
7.000398691872786
(4, 1)
7.000398691513792
(4, 1)
7.000398691155306
(4, 1)
7.000398690797331
(4, 1)
7.000398690439864
(4, 1)
7.000398690082904
(4, 1)
7.000398689726452
(4, 1)
7.000398689370507
(4, 1)
7.000398689015065
(4, 1)
7.000398688660131
(4, 1)
7.0003986883057
(4, 1)
7.0003986879517734
(4, 1)
7.000398687598346
(4, 1)
7.000398687245421
(4, 1)
7.0003986868930035
(4, 1)
7.00039868654108
(4, 1)
7.000398686189661
(4, 1)
7.000398685838736
(4, 1)
7.000398685488318
(4, 1)
7.000398685138392
(4, 1)
7.000398684788961
(4, 1)
7.000398684440031
(4, 1)
7.000398684091593
(4, 1)
7.000398683743652
(4, 1)
7.000398683396204
(4, 1)
7.000398683049251
(4, 1)
7.000398682702791
(4, 1)
7.000398682356821
(4, 1)
7.000398682011346
(4, 1)
7.000398681666361
(4, 1)
7.0003986813218635
(4, 1)
7.000398680977857
(4, 1)
7.000398680634339
(4, 1)
7.000398680291309
(4, 1)
7.0003986799487645
(4, 1)
7.0003986796067

(4, 1)
7.000398556443301
(4, 1)
7.000398556276688
(4, 1)
7.00039855611031
(4, 1)
7.00039855594417
(4, 1)
7.000398555778265
(4, 1)
7.000398555612595
(4, 1)
7.000398555447162
(4, 1)
7.000398555281964
(4, 1)
7.000398555117001
(4, 1)
7.0003985549522705
(4, 1)
7.000398554787773
(4, 1)
7.00039855462351
(4, 1)
7.000398554459481
(4, 1)
7.0003985542956855
(4, 1)
7.000398554132123
(4, 1)
7.000398553968793
(4, 1)
7.000398553805692
(4, 1)
7.000398553642825
(4, 1)
7.0003985534801885
(4, 1)
7.000398553317785
(4, 1)
7.000398553155609
(4, 1)
7.000398552993666
(4, 1)
7.000398552831952
(4, 1)
7.00039855267047
(4, 1)
7.000398552509213
(4, 1)
7.000398552348186
(4, 1)
7.000398552187392
(4, 1)
7.000398552026824
(4, 1)
7.0003985518664855
(4, 1)
7.000398551706371
(4, 1)
7.000398551546486
(4, 1)
7.0003985513868265
(4, 1)
7.000398551227396
(4, 1)
7.0003985510681925
(4, 1)
7.000398550909215
(4, 1)
7.000398550750461
(4, 1)
7.000398550591932
(4, 1)
7.000398550433632
(4, 1)
7.000398550275554
(4, 1)
7.00039855011770

7.000398492592026
(4, 1)
7.000398492516113
(4, 1)
7.0003984924403095
(4, 1)
7.000398492364615
(4, 1)
7.000398492289026
(4, 1)
7.0003984922135425
(4, 1)
7.00039849213817
(4, 1)
7.000398492062903
(4, 1)
7.000398491987742
(4, 1)
7.000398491912689
(4, 1)
7.0003984918377435
(4, 1)
7.000398491762902
(4, 1)
7.000398491688168
(4, 1)
7.000398491613538
(4, 1)
7.000398491539018
(4, 1)
7.000398491464602
(4, 1)
7.000398491390291
(4, 1)
7.000398491316086
(4, 1)
7.0003984912419845
(4, 1)
7.000398491167991
(4, 1)
7.000398491094106
(4, 1)
7.000398491020322
(4, 1)
7.000398490946641
(4, 1)
7.000398490873064
(4, 1)
7.000398490799594
(4, 1)
7.000398490726231
(4, 1)
7.000398490652968
(4, 1)
7.000398490579811
(4, 1)
7.0003984905067576
(4, 1)
7.000398490433808
(4, 1)
7.000398490360964
(4, 1)
7.000398490288223
(4, 1)
7.000398490215581
(4, 1)
7.000398490143047
(4, 1)
7.000398490070616
(4, 1)
7.000398489998282
(4, 1)
7.000398489926058
(4, 1)
7.00039848985393
(4, 1)
7.000398489781908
(4, 1)
7.0003984897099905
(4,

7.000398463225127
(4, 1)
7.000398463190928
(4, 1)
7.000398463156783
(4, 1)
7.000398463122683
(4, 1)
7.000398463088634
(4, 1)
7.000398463054635
(4, 1)
7.00039846302068
(4, 1)
7.000398462986775
(4, 1)
7.000398462952919
(4, 1)
7.00039846291911
(4, 1)
7.00039846288535
(4, 1)
7.000398462851635
(4, 1)
7.000398462817972
(4, 1)
7.000398462784354
(4, 1)
7.000398462750784
(4, 1)
7.000398462717264
(4, 1)
7.000398462683791
(4, 1)
7.000398462650363
(4, 1)
7.000398462616982
(4, 1)
7.000398462583652
(4, 1)
7.0003984625503675
(4, 1)
7.000398462517129
(4, 1)
7.000398462483941
(4, 1)
7.000398462450799
(4, 1)
7.000398462417705
(4, 1)
7.000398462384652
(4, 1)
7.000398462351652
(4, 1)
7.0003984623186986
(4, 1)
7.0003984622857915
(4, 1)
7.00039846225293
(4, 1)
7.000398462220115
(4, 1)
7.000398462187349
(4, 1)
7.000398462154626
(4, 1)
7.000398462121952
(4, 1)
7.000398462089325
(4, 1)
7.000398462056743
(4, 1)
7.000398462024205
(4, 1)
7.000398461991719
(4, 1)
7.000398461959273
(4, 1)
7.000398461926877
(4, 1)
7

7.000398449813027
(4, 1)
7.000398449797884
(4, 1)
7.000398449782759
(4, 1)
7.000398449767661
(4, 1)
7.0003984497525815
(4, 1)
7.0003984497375225
(4, 1)
7.00039844972249
(4, 1)
7.000398449707474
(4, 1)
7.000398449692481
(4, 1)
7.000398449677509
(4, 1)
7.000398449662558
(4, 1)
7.000398449647629
(4, 1)
7.000398449632719
(4, 1)
7.000398449617834
(4, 1)
7.000398449602966
(4, 1)
7.0003984495881255
(4, 1)
7.0003984495733
(4, 1)
7.000398449558498
(4, 1)
7.000398449543714
(4, 1)
7.0003984495289515
(4, 1)
7.000398449514212
(4, 1)
7.000398449499497
(4, 1)
7.0003984494847975
(4, 1)
7.000398449470118
(4, 1)
7.000398449455465
(4, 1)
7.00039844944083
(4, 1)
7.000398449426216
(4, 1)
7.00039844941162
(4, 1)
7.0003984493970455
(4, 1)
7.0003984493824944
(4, 1)
7.000398449367965
(4, 1)
7.000398449353454
(4, 1)
7.000398449338964
(4, 1)
7.00039844932449
(4, 1)
7.000398449310045
(4, 1)
7.000398449295616
(4, 1)
7.000398449281208
(4, 1)
7.00039844926682
(4, 1)
7.000398449252452
(4, 1)
7.000398449238103
(4, 1)


7.000398443826822
(4, 1)
7.0003984438201785
(4, 1)
7.000398443813552
(4, 1)
7.0003984438069295
(4, 1)
7.000398443800319
(4, 1)
7.000398443793716
(4, 1)
7.000398443787124
(4, 1)
7.000398443780539
(4, 1)
7.000398443773967
(4, 1)
7.000398443767403
(4, 1)
7.000398443760845
(4, 1)
7.0003984437543
(4, 1)
7.000398443747762
(4, 1)
7.000398443741239
(4, 1)
7.000398443734717
(4, 1)
7.00039844372821
(4, 1)
7.000398443721711
(4, 1)
7.00039844371522
(4, 1)
7.000398443708739
(4, 1)
7.000398443702267
(4, 1)
7.000398443695804
(4, 1)
7.000398443689349
(4, 1)
7.000398443682905
(4, 1)
7.000398443676469
(4, 1)
7.000398443670046
(4, 1)
7.000398443663626
(4, 1)
7.000398443657218
(4, 1)
7.0003984436508215
(4, 1)
7.000398443644429
(4, 1)
7.0003984436380495
(4, 1)
7.000398443631679
(4, 1)
7.000398443625315
(4, 1)
7.000398443618963
(4, 1)
7.000398443612616
(4, 1)
7.000398443606287
(4, 1)
7.000398443599956
(4, 1)
7.000398443593637
(4, 1)
7.000398443587332
(4, 1)
7.000398443581035
(4, 1)
7.000398443574741
(4, 1)


7.000398441267218
(4, 1)
7.000398441264214
(4, 1)
7.000398441261218
(4, 1)
7.0003984412582225
(4, 1)
7.000398441255233
(4, 1)
7.000398441252244
(4, 1)
7.000398441249262
(4, 1)
7.0003984412462845
(4, 1)
7.000398441243312
(4, 1)
7.000398441240342
(4, 1)
7.000398441237375
(4, 1)
7.000398441234415
(4, 1)
7.000398441231458
(4, 1)
7.000398441228502
(4, 1)
7.000398441225555
(4, 1)
7.000398441222611
(4, 1)
7.0003984412196685
(4, 1)
7.000398441216731
(4, 1)
7.000398441213801
(4, 1)
7.000398441210877
(4, 1)
7.000398441207949
(4, 1)
7.00039844120503
(4, 1)
7.0003984412021145
(4, 1)
7.000398441199205
(4, 1)
7.000398441196298
(4, 1)
7.0003984411933935
(4, 1)
7.000398441190496
(4, 1)
7.000398441187601
(4, 1)
7.000398441184708
(4, 1)
7.000398441181822
(4, 1)
7.000398441178939
(4, 1)
7.0003984411760625
(4, 1)
7.000398441173188
(4, 1)
7.000398441170317
(4, 1)
7.0003984411674525
(4, 1)
7.00039844116459
(4, 1)
7.000398441161733
(4, 1)
7.00039844115888
(4, 1)
7.000398441156027
(4, 1)
7.000398441153186
(4,

7.000398440116113
(4, 1)
7.000398440114745
(4, 1)
7.000398440113377
(4, 1)
7.000398440112012
(4, 1)
7.000398440110649
(4, 1)
7.000398440109288
(4, 1)
7.00039844010793
(4, 1)
7.000398440106574
(4, 1)
7.000398440105219
(4, 1)
7.000398440103865
(4, 1)
7.000398440102513
(4, 1)
7.000398440101162
(4, 1)
7.0003984400998185
(4, 1)
7.000398440098474
(4, 1)
7.00039844009713
(4, 1)
7.000398440095785
(4, 1)
7.000398440094446
(4, 1)
7.000398440093109
(4, 1)
7.000398440091772
(4, 1)
7.000398440090439
(4, 1)
7.00039844008911
(4, 1)
7.000398440087779
(4, 1)
7.000398440086447
(4, 1)
7.000398440085124
(4, 1)
7.000398440083798
(4, 1)
7.000398440082475
(4, 1)
7.0003984400811525
(4, 1)
7.000398440079834
(4, 1)
7.000398440078518
(4, 1)
7.000398440077205
(4, 1)
7.000398440075888
(4, 1)
7.000398440074582
(4, 1)
7.000398440073268
(4, 1)
7.000398440071964
(4, 1)
7.000398440070658
(4, 1)
7.000398440069353
(4, 1)
7.000398440068051
(4, 1)
7.000398440066752
(4, 1)
7.000398440065452
(4, 1)
7.0003984400641555
(4, 1)


(4, 1)
7.000398439586071
(4, 1)
7.000398439585455
(4, 1)
7.000398439584839
(4, 1)
7.0003984395842265
(4, 1)
7.000398439583613
(4, 1)
7.000398439583002
(4, 1)
7.000398439582391
(4, 1)
7.0003984395817795
(4, 1)
7.0003984395811685
(4, 1)
7.000398439580558
(4, 1)
7.000398439579952
(4, 1)
7.000398439579348
(4, 1)
7.000398439578739
(4, 1)
7.000398439578137
(4, 1)
7.000398439577529
(4, 1)
7.000398439576927
(4, 1)
7.000398439576325
(4, 1)
7.000398439575724
(4, 1)
7.000398439575123
(4, 1)
7.0003984395745205
(4, 1)
7.000398439573922
(4, 1)
7.000398439573327
(4, 1)
7.0003984395727255
(4, 1)
7.000398439572131
(4, 1)
7.000398439571536
(4, 1)
7.000398439570942
(4, 1)
7.000398439570345
(4, 1)
7.000398439569753
(4, 1)
7.00039843956916
(4, 1)
7.000398439568566
(4, 1)
7.000398439567976
(4, 1)
7.000398439567387
(4, 1)
7.000398439566799
(4, 1)
7.0003984395662116
(4, 1)
7.000398439565624
(4, 1)
7.000398439565034
(4, 1)
7.0003984395644485
(4, 1)
7.000398439563866
(4, 1)
7.000398439563283
(4, 1)
7.0003984395

(4, 1)
7.0003984393482
(4, 1)
7.00039843934792
(4, 1)
7.000398439347646
(4, 1)
7.000398439347366
(4, 1)
7.000398439347091
(4, 1)
7.000398439346816
(4, 1)
7.000398439346541
(4, 1)
7.000398439346264
(4, 1)
7.000398439345991
(4, 1)
7.000398439345714
(4, 1)
7.0003984393454415
(4, 1)
7.000398439345166
(4, 1)
7.0003984393448935
(4, 1)
7.000398439344622
(4, 1)
7.000398439344346
(4, 1)
7.000398439344076
(4, 1)
7.000398439343801
(4, 1)
7.000398439343534
(4, 1)
7.000398439343258
(4, 1)
7.000398439342993
(4, 1)
7.000398439342723
(4, 1)
7.00039843934245
(4, 1)
7.000398439342182
(4, 1)
7.000398439341912
(4, 1)
7.000398439341644
(4, 1)
7.000398439341374
(4, 1)
7.000398439341105
(4, 1)
7.000398439340838
(4, 1)
7.0003984393405725
(4, 1)
7.000398439340304
(4, 1)
7.000398439340037
(4, 1)
7.000398439339771
(4, 1)
7.000398439339506
(4, 1)
7.00039843933924
(4, 1)
7.000398439338975
(4, 1)
7.000398439338711
(4, 1)
7.000398439338445
(4, 1)
7.000398439338182
(4, 1)
7.0003984393379195
(4, 1)
7.000398439337658
(

(4, 1)
7.000398439241524
(4, 1)
7.000398439241399
(4, 1)
7.000398439241274
(4, 1)
7.000398439241145
(4, 1)
7.000398439241023
(4, 1)
7.000398439240896
(4, 1)
7.000398439240771
(4, 1)
7.000398439240647
(4, 1)
7.00039843924052
(4, 1)
7.0003984392403975
(4, 1)
7.000398439240271
(4, 1)
7.000398439240149
(4, 1)
7.000398439240022
(4, 1)
7.0003984392399
(4, 1)
7.000398439239773
(4, 1)
7.0003984392396505
(4, 1)
7.000398439239531
(4, 1)
7.000398439239406
(4, 1)
7.000398439239282
(4, 1)
7.000398439239157
(4, 1)
7.000398439239035
(4, 1)
7.000398439238915
(4, 1)
7.000398439238791
(4, 1)
7.000398439238671
(4, 1)
7.0003984392385465
(4, 1)
7.000398439238424
(4, 1)
7.000398439238301
(4, 1)
7.0003984392381815
(4, 1)
7.00039843923806
(4, 1)
7.000398439237937
(4, 1)
7.000398439237816
(4, 1)
7.0003984392376974
(4, 1)
7.0003984392375775
(4, 1)
7.000398439237453
(4, 1)
7.000398439237336
(4, 1)
7.000398439237213
(4, 1)
7.000398439237096
(4, 1)
7.0003984392369745
(4, 1)
7.000398439236855
(4, 1)
7.0003984392367

(4, 1)
7.000398439192776
(4, 1)
7.000398439192719
(4, 1)
7.000398439192661
(4, 1)
7.000398439192605
(4, 1)
7.000398439192548
(4, 1)
7.000398439192492
(4, 1)
7.000398439192435
(4, 1)
7.000398439192379
(4, 1)
7.000398439192322
(4, 1)
7.000398439192266
(4, 1)
7.000398439192209
(4, 1)
7.000398439192155
(4, 1)
7.000398439192097
(4, 1)
7.000398439192042
(4, 1)
7.0003984391919865
(4, 1)
7.000398439191928
(4, 1)
7.000398439191874
(4, 1)
7.0003984391918195
(4, 1)
7.000398439191763
(4, 1)
7.000398439191707
(4, 1)
7.0003984391916525
(4, 1)
7.0003984391915965
(4, 1)
7.000398439191542
(4, 1)
7.0003984391914855
(4, 1)
7.000398439191434
(4, 1)
7.000398439191375
(4, 1)
7.000398439191321
(4, 1)
7.000398439191267
(4, 1)
7.000398439191208
(4, 1)
7.000398439191157
(4, 1)
7.000398439191103
(4, 1)
7.0003984391910485
(4, 1)
7.000398439190993
(4, 1)
7.000398439190938
(4, 1)
7.000398439190884
(4, 1)
7.00039843919083
(4, 1)
7.000398439190776
(4, 1)
7.000398439190722
(4, 1)
7.000398439190666
(4, 1)
7.00039843919

(4, 1)
7.000398439170756
(4, 1)
7.000398439170731
(4, 1)
7.000398439170705
(4, 1)
7.000398439170679
(4, 1)
7.000398439170658
(4, 1)
7.000398439170632
(4, 1)
7.000398439170604
(4, 1)
7.0003984391705805
(4, 1)
7.000398439170552
(4, 1)
7.000398439170529
(4, 1)
7.0003984391705005
(4, 1)
7.000398439170479
(4, 1)
7.0003984391704535
(4, 1)
7.000398439170428
(4, 1)
7.000398439170402
(4, 1)
7.000398439170376
(4, 1)
7.000398439170355
(4, 1)
7.0003984391703264
(4, 1)
7.000398439170303
(4, 1)
7.000398439170279
(4, 1)
7.000398439170252
(4, 1)
7.000398439170228
(4, 1)
7.000398439170202
(4, 1)
7.000398439170174
(4, 1)
7.000398439170152
(4, 1)
7.000398439170127
(4, 1)
7.0003984391701035
(4, 1)
7.000398439170075
(4, 1)
7.000398439170054
(4, 1)
7.000398439170028
(4, 1)
7.000398439170005
(4, 1)
7.000398439169979
(4, 1)
7.000398439169953
(4, 1)
7.000398439169929
(4, 1)
7.000398439169906
(4, 1)
7.000398439169882
(4, 1)
7.000398439169857
(4, 1)
7.0003984391698335
(4, 1)
7.0003984391698095
(4, 1)
7.000398439

7.0003984391606915
(4, 1)
7.00039843916068
(4, 1)
7.000398439160668
(4, 1)
7.000398439160657
(4, 1)
7.000398439160647
(4, 1)
7.000398439160633
(4, 1)
7.000398439160621
(4, 1)
7.0003984391606116
(4, 1)
7.000398439160603
(4, 1)
7.0003984391605885
(4, 1)
7.000398439160577
(4, 1)
7.000398439160567
(4, 1)
7.000398439160556
(4, 1)
7.000398439160546
(4, 1)
7.000398439160534
(4, 1)
7.000398439160523
(4, 1)
7.0003984391605085
(4, 1)
7.000398439160501
(4, 1)
7.000398439160487
(4, 1)
7.000398439160476
(4, 1)
7.000398439160466
(4, 1)
7.000398439160454
(4, 1)
7.000398439160443
(4, 1)
7.000398439160433
(4, 1)
7.000398439160424
(4, 1)
7.000398439160412
(4, 1)
7.0003984391604
(4, 1)
7.000398439160391
(4, 1)
7.0003984391603815
(4, 1)
7.000398439160367
(4, 1)
7.000398439160356
(4, 1)
7.000398439160344
(4, 1)
7.000398439160337
(4, 1)
7.000398439160323
(4, 1)
7.000398439160313
(4, 1)
7.000398439160306
(4, 1)
7.0003984391602945
(4, 1)
7.00039843916028
(4, 1)
7.000398439160271
(4, 1)
7.000398439160259
(4, 1

(4, 1)
7.000398439156291
(4, 1)
7.000398439156285
(4, 1)
7.000398439156281
(4, 1)
7.000398439156276
(4, 1)
7.000398439156269
(4, 1)
7.000398439156265
(4, 1)
7.0003984391562595
(4, 1)
7.000398439156252
(4, 1)
7.000398439156245
(4, 1)
7.0003984391562435
(4, 1)
7.000398439156238
(4, 1)
7.000398439156234
(4, 1)
7.000398439156229
(4, 1)
7.000398439156222
(4, 1)
7.0003984391562195
(4, 1)
7.000398439156212
(4, 1)
7.000398439156208
(4, 1)
7.000398439156205
(4, 1)
7.000398439156196
(4, 1)
7.000398439156194
(4, 1)
7.000398439156189
(4, 1)
7.000398439156182
(4, 1)
7.0003984391561795
(4, 1)
7.000398439156172
(4, 1)
7.000398439156171
(4, 1)
7.000398439156165
(4, 1)
7.000398439156159
(4, 1)
7.000398439156154
(4, 1)
7.000398439156149
(4, 1)
7.000398439156145
(4, 1)
7.000398439156142
(4, 1)
7.000398439156138
(4, 1)
7.000398439156131
(4, 1)
7.000398439156128
(4, 1)
7.000398439156121
(4, 1)
7.0003984391561165
(4, 1)
7.000398439156109
(4, 1)
7.000398439156107
(4, 1)
7.0003984391561
(4, 1)
7.0003984391560

In [37]:
l

7.000398439154387

In [38]:
A

array([[-0.08449282],
       [-0.02356189],
       [ 0.22487156],
       [ 0.59972196]])

In [39]:
A.shape

(4, 1)

In [40]:
ypreds=x.dot(A)

In [41]:
print(np.sqrt(metrics.mean_squared_error(ypreds,y)))

0.21603083790907246


In [42]:
ypreds

array([[-7.86154106e-02],
       [-4.99359018e-02],
       [-6.02368725e-02],
       [-4.45709029e-03],
       [-7.25223181e-02],
       [ 7.40178465e-02],
       [ 2.59593823e-02],
       [-4.53227842e-02],
       [-5.33330454e-03],
       [-8.97771308e-02],
       [-8.61884780e-02],
       [-5.93706514e-03],
       [-1.01458816e-01],
       [-1.26673875e-01],
       [-1.94515639e-01],
       [-8.08525540e-03],
       [-1.59307764e-02],
       [-1.86432150e-02],
       [-8.94600494e-03],
       [-3.22462658e-03],
       [-3.41455992e-02],
       [ 5.91037582e-02],
       [-1.28673814e-01],
       [ 1.73475022e-01],
       [ 6.15244021e-02],
       [-1.34108720e-02],
       [ 9.71087628e-02],
       [-6.45775365e-02],
       [-8.47085032e-02],
       [ 7.22459470e-03],
       [ 1.13150217e-03],
       [ 4.08244805e-02],
       [-1.38686867e-01],
       [-1.28905861e-01],
       [-2.98049352e-02],
       [-1.08071873e-01],
       [-1.34899693e-01],
       [-1.24045232e-01],
       [-3.0

In [43]:
for i in range(len(ypreds)):
    ypreds[i]=int(np.round(ypreds[i]))
    if ypreds[i]<0:
        ypreds[i]=-ypreds[i]

In [45]:
ypreds

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [46]:
metrics.accuracy_score(ypreds,y)

0.9666666666666667

We can observe that the accuracy is almost same in the above three methods.